version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: flask_blog_4320_image
    container_name: flask-blog-4320-container
    ports: 
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_debug: 1